@startuml
actor RoadReader
actor ExternalReader
actor Site Administrator
actor AddressEditor
actor RoadEditor
actor Member
actor Contributor
actor Manager
actor Editor
actor Anonymous
actor Reader
actor Owner
actor Reviewer
actor InternalReader
usecase "Modify portal content" as UC1
Manager --> UC1
Owner --> UC1
Editor --> UC1
Site Administrator --> UC1
usecase "Access contents information" as UC2
Anonymous --> UC2
usecase "View" as UC3
Anonymous --> UC3
usecase "Modify portal content" as UC4
Manager --> UC4
Owner --> UC4
Editor --> UC4
Site Administrator --> UC4
usecase "Access contents information" as UC5
Manager --> UC5
Owner --> UC5
Editor --> UC5
Reader --> UC5
Contributor --> UC5
Site Administrator --> UC5
usecase "View" as UC6
Manager --> UC6
Owner --> UC6
Editor --> UC6
Reader --> UC6
Contributor --> UC6
Site Administrator --> UC6
usecase "Modify portal content" as UC7
Manager --> UC7
Owner --> UC7
Editor --> UC7
Site Administrator --> UC7
usecase "Access contents information" as UC8
Anonymous --> UC8
usecase "View" as UC9
Anonymous --> UC9
usecase "Modify portal content" as UC10
Manager --> UC10
Owner --> UC10
Editor --> UC10
Site Administrator --> UC10
usecase "Access contents information" as UC11
Manager --> UC11
Owner --> UC11
Editor --> UC11
Reader --> UC11
Contributor --> UC11
Member --> UC11
Site Administrator --> UC11
usecase "View" as UC12
Manager --> UC12
Owner --> UC12
Editor --> UC12
Reader --> UC12
Contributor --> UC12
Member --> UC12
Site Administrator --> UC12
usecase "Modify portal content" as UC13
Manager --> UC13
Owner --> UC13
Editor --> UC13
Site Administrator --> UC13
usecase "Access contents information" as UC14
Manager --> UC14
Owner --> UC14
Editor --> UC14
Reader --> UC14
Contributor --> UC14
Site Administrator --> UC14
usecase "View" as UC15
Manager --> UC15
Owner --> UC15
Editor --> UC15
Reader --> UC15
Contributor --> UC15
Site Administrator --> UC15
usecase "Change portal events" as UC16
Manager --> UC16
Site Administrator --> UC16
usecase "Modify portal content" as UC17
Manager --> UC17
Site Administrator --> UC17
usecase "Access contents information" as UC18
Manager --> UC18
Owner --> UC18
Editor --> UC18
Reader --> UC18
Contributor --> UC18
Member --> UC18
Site Administrator --> UC18
usecase "View" as UC19
Manager --> UC19
Owner --> UC19
Editor --> UC19
Reader --> UC19
Contributor --> UC19
Member --> UC19
Site Administrator --> UC19
usecase "Change portal events" as UC20
Manager --> UC20
Owner --> UC20
Editor --> UC20
Site Administrator --> UC20
usecase "Modify portal content" as UC21
Manager --> UC21
Owner --> UC21
Editor --> UC21
Site Administrator --> UC21
usecase "Access contents information" as UC22
Manager --> UC22
Owner --> UC22
Editor --> UC22
Reader --> UC22
Contributor --> UC22
Member --> UC22
Site Administrator --> UC22
usecase "View" as UC23
Manager --> UC23
Owner --> UC23
Editor --> UC23
Reader --> UC23
Contributor --> UC23
Member --> UC23
Site Administrator --> UC23
usecase "Change portal events" as UC24
Manager --> UC24
Reviewer --> UC24
Site Administrator --> UC24
usecase "Modify portal content" as UC25
Manager --> UC25
Reviewer --> UC25
Site Administrator --> UC25
usecase "Access contents information" as UC26
Manager --> UC26
Owner --> UC26
Editor --> UC26
Reader --> UC26
Contributor --> UC26
Member --> UC26
Reviewer --> UC26
Site Administrator --> UC26
usecase "View" as UC27
Manager --> UC27
Owner --> UC27
Editor --> UC27
Reader --> UC27
Contributor --> UC27
Member --> UC27
Reviewer --> UC27
Site Administrator --> UC27
usecase "Change portal events" as UC28
Manager --> UC28
Owner --> UC28
Editor --> UC28
Site Administrator --> UC28
usecase "Modify portal content" as UC29
Manager --> UC29
Owner --> UC29
Editor --> UC29
Site Administrator --> UC29
usecase "Access contents information" as UC30
Manager --> UC30
Owner --> UC30
Editor --> UC30
Reader --> UC30
Contributor --> UC30
Site Administrator --> UC30
usecase "View" as UC31
Manager --> UC31
Owner --> UC31
Editor --> UC31
Reader --> UC31
Contributor --> UC31
Site Administrator --> UC31
usecase "Change portal events" as UC32
Manager --> UC32
Site Administrator --> UC32
usecase "Modify portal content" as UC33
Manager --> UC33
Site Administrator --> UC33
usecase "Access contents information" as UC34
Anonymous --> UC34
usecase "View" as UC35
Anonymous --> UC35
usecase "Change portal events" as UC36
Manager --> UC36
Owner --> UC36
Editor --> UC36
Site Administrator --> UC36
usecase "Modify portal content" as UC37
Manager --> UC37
Owner --> UC37
Editor --> UC37
Site Administrator --> UC37
usecase "Access contents information" as UC38
Anonymous --> UC38
usecase "View" as UC39
Anonymous --> UC39
usecase "Change portal events" as UC40
Manager --> UC40
Owner --> UC40
Editor --> UC40
Site Administrator --> UC40
usecase "Modify portal content" as UC41
Manager --> UC41
Owner --> UC41
Editor --> UC41
Site Administrator --> UC41
usecase "Access contents information" as UC42
Anonymous --> UC42
usecase "View" as UC43
Anonymous --> UC43
usecase "Change portal events" as UC44
Manager --> UC44
Reviewer --> UC44
Site Administrator --> UC44
usecase "Modify portal content" as UC45
Manager --> UC45
Reviewer --> UC45
Site Administrator --> UC45
usecase "Access contents information" as UC46
Anonymous --> UC46
usecase "View" as UC47
Anonymous --> UC47
usecase "Change portal events" as UC48
Manager --> UC48
Owner --> UC48
Editor --> UC48
Site Administrator --> UC48
usecase "Modify portal content" as UC49
Manager --> UC49
Owner --> UC49
Editor --> UC49
Site Administrator --> UC49
usecase "Access contents information" as UC50
Manager --> UC50
Owner --> UC50
Reader --> UC50
Editor --> UC50
Contributor --> UC50
Site Administrator --> UC50
usecase "View" as UC51
Manager --> UC51
Owner --> UC51
Reader --> UC51
Editor --> UC51
Contributor --> UC51
Site Administrator --> UC51
usecase "Change portal events" as UC52
Manager --> UC52
Site Administrator --> UC52
usecase "Modify portal content" as UC53
Manager --> UC53
Site Administrator --> UC53
usecase "Access contents information" as UC54
Anonymous --> UC54
usecase "View" as UC55
Anonymous --> UC55
usecase "Change portal events" as UC56
Manager --> UC56
Reviewer --> UC56
Site Administrator --> UC56
usecase "Modify portal content" as UC57
Manager --> UC57
Reviewer --> UC57
Site Administrator --> UC57
usecase "Access contents information" as UC58
Manager --> UC58
Owner --> UC58
Editor --> UC58
Reader --> UC58
Contributor --> UC58
Reviewer --> UC58
Site Administrator --> UC58
usecase "View" as UC59
Manager --> UC59
Owner --> UC59
Editor --> UC59
Reader --> UC59
Contributor --> UC59
Reviewer --> UC59
Site Administrator --> UC59
usecase "Change portal events" as UC60
Manager --> UC60
Owner --> UC60
Editor --> UC60
Site Administrator --> UC60
usecase "Modify portal content" as UC61
Manager --> UC61
Owner --> UC61
Editor --> UC61
Site Administrator --> UC61
usecase "Access contents information" as UC62
Manager --> UC62
Owner --> UC62
Editor --> UC62
Reader --> UC62
Contributor --> UC62
Site Administrator --> UC62
usecase "View" as UC63
Manager --> UC63
Owner --> UC63
Editor --> UC63
Reader --> UC63
Contributor --> UC63
Site Administrator --> UC63
usecase "Change portal events" as UC64
Manager --> UC64
Owner --> UC64
Editor --> UC64
Site Administrator --> UC64
usecase "Modify portal content" as UC65
Manager --> UC65
Owner --> UC65
Editor --> UC65
Site Administrator --> UC65
usecase "Access contents information" as UC66
Anonymous --> UC66
usecase "View" as UC67
Anonymous --> UC67
usecase "Modify portal content" as UC68
Manager --> UC68
Owner --> UC68
Reviewer --> UC68
usecase "Access contents information" as UC69
Manager --> UC69
Owner --> UC69
Reviewer --> UC69
usecase "Reply to item" as UC70
usecase "View" as UC71
Manager --> UC71
Owner --> UC71
Reviewer --> UC71
usecase "Modify portal content" as UC72
Manager --> UC72
usecase "Access contents information" as UC73
usecase "Reply to item" as UC74
usecase "View" as UC75
usecase "Change portal events" as UC76
Manager --> UC76
Owner --> UC76
Editor --> UC76
Site Administrator --> UC76
usecase "Modify portal content" as UC77
Manager --> UC77
Owner --> UC77
Editor --> UC77
Site Administrator --> UC77
usecase "Access contents information" as UC78
Anonymous --> UC78
usecase "View" as UC79
usecase "Review portal content" as UC80
Manager --> UC80
Reviewer --> UC80
Site Administrator --> UC80
usecase "Modify portal content" as UC81
Editor --> UC81
Manager --> UC81
Site Administrator --> UC81
usecase "Delete objects" as UC82
Manager --> UC82
Site Administrator --> UC82
usecase "Request review" as UC83
Editor --> UC83
Manager --> UC83
Site Administrator --> UC83
usecase "Access contents information" as UC84
Contributor --> UC84
Editor --> UC84
Manager --> UC84
Owner --> UC84
Reader --> UC84
Reviewer --> UC84
Site Administrator --> UC84
usecase "View" as UC85
Contributor --> UC85
Editor --> UC85
Manager --> UC85
Owner --> UC85
Reader --> UC85
Reviewer --> UC85
Site Administrator --> UC85
usecase "Review portal content" as UC86
Manager --> UC86
Reviewer --> UC86
Site Administrator --> UC86
usecase "Modify portal content" as UC87
Editor --> UC87
Manager --> UC87
Site Administrator --> UC87
usecase "Delete objects" as UC88
Manager --> UC88
Site Administrator --> UC88
usecase "Request review" as UC89
Editor --> UC89
Manager --> UC89
Site Administrator --> UC89
usecase "Access contents information" as UC90
Contributor --> UC90
Editor --> UC90
Manager --> UC90
Owner --> UC90
Reader --> UC90
Reviewer --> UC90
Site Administrator --> UC90
usecase "View" as UC91
Contributor --> UC91
Editor --> UC91
Manager --> UC91
Owner --> UC91
Reader --> UC91
Reviewer --> UC91
Site Administrator --> UC91
usecase "Review portal content" as UC92
Contributor --> UC92
Manager --> UC92
Reviewer --> UC92
Site Administrator --> UC92
usecase "Modify portal content" as UC93
Contributor --> UC93
Editor --> UC93
Manager --> UC93
Owner --> UC93
Site Administrator --> UC93
usecase "Delete objects" as UC94
Contributor --> UC94
Editor --> UC94
Manager --> UC94
Owner --> UC94
Site Administrator --> UC94
usecase "Add portal content" as UC95
usecase "Request review" as UC96
Contributor --> UC96
Editor --> UC96
Manager --> UC96
Owner --> UC96
Site Administrator --> UC96
usecase "Access contents information" as UC97
Contributor --> UC97
Editor --> UC97
Manager --> UC97
Owner --> UC97
Reader --> UC97
Reviewer --> UC97
Site Administrator --> UC97
usecase "View" as UC98
Contributor --> UC98
Editor --> UC98
Manager --> UC98
Owner --> UC98
Reader --> UC98
Reviewer --> UC98
Site Administrator --> UC98
usecase "Review portal content" as UC99
Manager --> UC99
Reviewer --> UC99
Site Administrator --> UC99
usecase "Modify portal content" as UC100
Editor --> UC100
Manager --> UC100
Site Administrator --> UC100
usecase "Delete objects" as UC101
Manager --> UC101
Site Administrator --> UC101
usecase "Request review" as UC102
Editor --> UC102
Manager --> UC102
Site Administrator --> UC102
usecase "Access contents information" as UC103
Contributor --> UC103
Editor --> UC103
Manager --> UC103
Owner --> UC103
Reader --> UC103
Reviewer --> UC103
Site Administrator --> UC103
usecase "View" as UC104
Contributor --> UC104
Editor --> UC104
Manager --> UC104
Owner --> UC104
Reader --> UC104
Reviewer --> UC104
Site Administrator --> UC104
usecase "Review portal content" as UC105
Manager --> UC105
Reviewer --> UC105
Site Administrator --> UC105
usecase "Modify portal content" as UC106
Editor --> UC106
Manager --> UC106
Site Administrator --> UC106
usecase "Delete objects" as UC107
Manager --> UC107
Site Administrator --> UC107
usecase "Request review" as UC108
Editor --> UC108
Manager --> UC108
Site Administrator --> UC108
usecase "Access contents information" as UC109
Contributor --> UC109
Editor --> UC109
Manager --> UC109
Owner --> UC109
Reader --> UC109
Reviewer --> UC109
Site Administrator --> UC109
usecase "View" as UC110
Contributor --> UC110
Editor --> UC110
Manager --> UC110
Owner --> UC110
Reader --> UC110
Reviewer --> UC110
Site Administrator --> UC110
usecase "Review portal content" as UC111
Manager --> UC111
Reviewer --> UC111
Site Administrator --> UC111
usecase "Modify portal content" as UC112
Editor --> UC112
Manager --> UC112
Site Administrator --> UC112
usecase "Delete objects" as UC113
Manager --> UC113
Site Administrator --> UC113
usecase "Request review" as UC114
Editor --> UC114
Manager --> UC114
Site Administrator --> UC114
usecase "Access contents information" as UC115
Contributor --> UC115
Editor --> UC115
Manager --> UC115
Owner --> UC115
Reader --> UC115
Reviewer --> UC115
Site Administrator --> UC115
usecase "View" as UC116
Contributor --> UC116
Editor --> UC116
Manager --> UC116
Owner --> UC116
Reader --> UC116
Reviewer --> UC116
Site Administrator --> UC116
usecase "Review portal content" as UC117
Manager --> UC117
Contributor --> UC117
Editor --> UC117
Owner --> UC117
usecase "Modify portal content" as UC118
Manager --> UC118
Contributor --> UC118
Editor --> UC118
Owner --> UC118
usecase "Acces contents information" as UC119
Reader --> UC119
Manager --> UC119
Contributor --> UC119
Editor --> UC119
Owner --> UC119
usecase "Delete objects" as UC120
Manager --> UC120
Contributor --> UC120
Editor --> UC120
Owner --> UC120
usecase "Access contents information" as UC121
Reader --> UC121
Manager --> UC121
Contributor --> UC121
Editor --> UC121
Owner --> UC121
usecase "View" as UC122
Reader --> UC122
Manager --> UC122
Contributor --> UC122
Editor --> UC122
Owner --> UC122
usecase "Review portal content" as UC123
Manager --> UC123
Contributor --> UC123
Editor --> UC123
Owner --> UC123
usecase "Modify portal content" as UC124
Manager --> UC124
Contributor --> UC124
Editor --> UC124
Owner --> UC124
usecase "Acces contents information" as UC125
Manager --> UC125
Contributor --> UC125
Reader --> UC125
Editor --> UC125
Owner --> UC125
usecase "Delete objects" as UC126
Manager --> UC126
Contributor --> UC126
Editor --> UC126
Owner --> UC126
usecase "Access contents information" as UC127
Manager --> UC127
Contributor --> UC127
Reader --> UC127
Editor --> UC127
Owner --> UC127
usecase "View" as UC128
Manager --> UC128
Contributor --> UC128
Reader --> UC128
Editor --> UC128
Owner --> UC128
usecase "Review portal content" as UC129
Reviewer --> UC129
Contributor --> UC129
Manager --> UC129
usecase "Modify portal content" as UC130
Editor --> UC130
Contributor --> UC130
Manager --> UC130
usecase "Acces contents information" as UC131
Reader --> UC131
Editor --> UC131
Contributor --> UC131
Manager --> UC131
usecase "Modify view template" as UC132
Manager --> UC132
usecase "Delete objects" as UC133
Editor --> UC133
Contributor --> UC133
Manager --> UC133
usecase "Add portal content" as UC134
Editor --> UC134
Contributor --> UC134
Manager --> UC134
usecase "Manage properties" as UC135
Contributor --> UC135
Editor --> UC135
Manager --> UC135
usecase "Access contents information" as UC136
Reader --> UC136
Editor --> UC136
Contributor --> UC136
Manager --> UC136
usecase "View" as UC137
Reader --> UC137
Editor --> UC137
Contributor --> UC137
Manager --> UC137
usecase "Review portal content" as UC138
Reviewer --> UC138
Manager --> UC138
usecase "Modify portal content" as UC139
Editor --> UC139
Contributor --> UC139
Manager --> UC139
usecase "Acces contents information" as UC140
Reader --> UC140
Editor --> UC140
Contributor --> UC140
Manager --> UC140
usecase "Modify view template" as UC141
Manager --> UC141
usecase "Delete objects" as UC142
Editor --> UC142
Contributor --> UC142
Manager --> UC142
usecase "Add portal content" as UC143
Editor --> UC143
Contributor --> UC143
Manager --> UC143
usecase "Manage properties" as UC144
Contributor --> UC144
Editor --> UC144
Manager --> UC144
usecase "Access contents information" as UC145
Reader --> UC145
Editor --> UC145
Contributor --> UC145
Manager --> UC145
usecase "View" as UC146
Reader --> UC146
Editor --> UC146
Contributor --> UC146
Manager --> UC146
usecase "Review portal content" as UC147
Reviewer --> UC147
Manager --> UC147
usecase "Modify portal content" as UC148
Editor --> UC148
Contributor --> UC148
Manager --> UC148
usecase "Acces contents information" as UC149
Reader --> UC149
Editor --> UC149
Contributor --> UC149
Manager --> UC149
usecase "Modify view template" as UC150
Manager --> UC150
usecase "Delete objects" as UC151
Editor --> UC151
Contributor --> UC151
Manager --> UC151
usecase "Add portal content" as UC152
Editor --> UC152
Contributor --> UC152
Manager --> UC152
usecase "Manage properties" as UC153
Contributor --> UC153
Editor --> UC153
Manager --> UC153
usecase "Access contents information" as UC154
Reader --> UC154
Editor --> UC154
Contributor --> UC154
Manager --> UC154
usecase "View" as UC155
Reader --> UC155
Editor --> UC155
Contributor --> UC155
Manager --> UC155
usecase "Review portal content" as UC156
Reviewer --> UC156
Contributor --> UC156
Manager --> UC156
usecase "Modify portal content" as UC157
Editor --> UC157
Contributor --> UC157
Manager --> UC157
usecase "Acces contents information" as UC158
Reader --> UC158
Editor --> UC158
Contributor --> UC158
Manager --> UC158
usecase "Modify view template" as UC159
Manager --> UC159
usecase "Delete objects" as UC160
Editor --> UC160
Contributor --> UC160
Manager --> UC160
usecase "Add portal content" as UC161
Editor --> UC161
Contributor --> UC161
Manager --> UC161
usecase "Manage properties" as UC162
Contributor --> UC162
Editor --> UC162
Manager --> UC162
usecase "Access contents information" as UC163
Reader --> UC163
Editor --> UC163
Contributor --> UC163
Manager --> UC163
usecase "View" as UC164
Reader --> UC164
Editor --> UC164
Contributor --> UC164
Manager --> UC164
usecase "Review portal content" as UC165
Reviewer --> UC165
Manager --> UC165
usecase "Modify portal content" as UC166
Editor --> UC166
Contributor --> UC166
Manager --> UC166
usecase "Acces contents information" as UC167
Reader --> UC167
Editor --> UC167
Contributor --> UC167
Manager --> UC167
usecase "Modify view template" as UC168
Manager --> UC168
usecase "Delete objects" as UC169
Editor --> UC169
Contributor --> UC169
Manager --> UC169
usecase "Add portal content" as UC170
Editor --> UC170
Contributor --> UC170
Manager --> UC170
usecase "Manage properties" as UC171
Contributor --> UC171
Editor --> UC171
Manager --> UC171
usecase "Access contents information" as UC172
Reader --> UC172
Editor --> UC172
Contributor --> UC172
Manager --> UC172
usecase "View" as UC173
Reader --> UC173
Editor --> UC173
Contributor --> UC173
Manager --> UC173
usecase "Review portal content" as UC174
Reviewer --> UC174
Manager --> UC174
usecase "Modify portal content" as UC175
Editor --> UC175
Contributor --> UC175
Manager --> UC175
usecase "Acces contents information" as UC176
Reader --> UC176
Editor --> UC176
Contributor --> UC176
Manager --> UC176
usecase "Modify view template" as UC177
Manager --> UC177
usecase "urban: Add CODT_Inquiry" as UC178
Editor --> UC178
Contributor --> UC178
Manager --> UC178
usecase "Delete objects" as UC179
Editor --> UC179
Contributor --> UC179
Manager --> UC179
usecase "Add portal content" as UC180
Editor --> UC180
Contributor --> UC180
Manager --> UC180
usecase "Manage properties" as UC181
Contributor --> UC181
Editor --> UC181
Manager --> UC181
usecase "Access contents information" as UC182
Reader --> UC182
Editor --> UC182
Contributor --> UC182
Manager --> UC182
usecase "View" as UC183
Reader --> UC183
Editor --> UC183
Contributor --> UC183
Manager --> UC183
usecase "Review portal content" as UC184
Reviewer --> UC184
Manager --> UC184
usecase "Modify portal content" as UC185
Editor --> UC185
Contributor --> UC185
Manager --> UC185
usecase "Acces contents information" as UC186
Reader --> UC186
Editor --> UC186
Contributor --> UC186
Manager --> UC186
usecase "Modify view template" as UC187
Manager --> UC187
usecase "urban: Add CODT_Inquiry" as UC188
Editor --> UC188
Contributor --> UC188
Manager --> UC188
usecase "Delete objects" as UC189
Editor --> UC189
Contributor --> UC189
Manager --> UC189
usecase "Add portal content" as UC190
Editor --> UC190
Contributor --> UC190
Manager --> UC190
usecase "Manage properties" as UC191
Contributor --> UC191
Editor --> UC191
Manager --> UC191
usecase "Access contents information" as UC192
Reader --> UC192
Editor --> UC192
Contributor --> UC192
Manager --> UC192
usecase "View" as UC193
Reader --> UC193
Editor --> UC193
Contributor --> UC193
Manager --> UC193
usecase "Review portal content" as UC194
Reviewer --> UC194
Manager --> UC194
usecase "Modify portal content" as UC195
Editor --> UC195
Contributor --> UC195
Manager --> UC195
usecase "Acces contents information" as UC196
Reader --> UC196
Editor --> UC196
Contributor --> UC196
Manager --> UC196
usecase "Modify view template" as UC197
Manager --> UC197
usecase "urban: Add CODT_Inquiry" as UC198
Editor --> UC198
Contributor --> UC198
Manager --> UC198
usecase "Delete objects" as UC199
Editor --> UC199
Contributor --> UC199
Manager --> UC199
usecase "Add portal content" as UC200
Editor --> UC200
Contributor --> UC200
Manager --> UC200
usecase "Manage properties" as UC201
Contributor --> UC201
Editor --> UC201
Manager --> UC201
usecase "Access contents information" as UC202
Reader --> UC202
Editor --> UC202
Contributor --> UC202
Manager --> UC202
usecase "View" as UC203
Reader --> UC203
Editor --> UC203
Contributor --> UC203
Manager --> UC203
usecase "Review portal content" as UC204
Reviewer --> UC204
Manager --> UC204
usecase "Modify portal content" as UC205
Editor --> UC205
Contributor --> UC205
Manager --> UC205
usecase "Acces contents information" as UC206
Reader --> UC206
Editor --> UC206
Contributor --> UC206
Manager --> UC206
usecase "Modify view template" as UC207
Manager --> UC207
usecase "urban: Add CODT_Inquiry" as UC208
Editor --> UC208
Contributor --> UC208
Manager --> UC208
usecase "Delete objects" as UC209
Editor --> UC209
Contributor --> UC209
Manager --> UC209
usecase "Add portal content" as UC210
Editor --> UC210
Contributor --> UC210
Manager --> UC210
usecase "Manage properties" as UC211
Contributor --> UC211
Editor --> UC211
Manager --> UC211
usecase "Access contents information" as UC212
Reader --> UC212
Editor --> UC212
Contributor --> UC212
Manager --> UC212
usecase "View" as UC213
Reader --> UC213
Editor --> UC213
Contributor --> UC213
Manager --> UC213
usecase "Review portal content" as UC214
Reviewer --> UC214
Manager --> UC214
usecase "Modify portal content" as UC215
Editor --> UC215
Contributor --> UC215
Manager --> UC215
usecase "Acces contents information" as UC216
Reader --> UC216
Editor --> UC216
Contributor --> UC216
Manager --> UC216
usecase "Modify view template" as UC217
Manager --> UC217
usecase "urban: Add CODT_Inquiry" as UC218
Editor --> UC218
Contributor --> UC218
Manager --> UC218
usecase "Delete objects" as UC219
Editor --> UC219
Contributor --> UC219
Manager --> UC219
usecase "Add portal content" as UC220
Editor --> UC220
Contributor --> UC220
Manager --> UC220
usecase "Manage properties" as UC221
Contributor --> UC221
Editor --> UC221
Manager --> UC221
usecase "Access contents information" as UC222
Reader --> UC222
Editor --> UC222
Contributor --> UC222
Manager --> UC222
usecase "View" as UC223
Reader --> UC223
Editor --> UC223
Contributor --> UC223
Manager --> UC223
usecase "Review portal content" as UC224
Reviewer --> UC224
Manager --> UC224
usecase "Modify portal content" as UC225
Editor --> UC225
Contributor --> UC225
Manager --> UC225
usecase "Acces contents information" as UC226
Reader --> UC226
Editor --> UC226
Contributor --> UC226
Manager --> UC226
usecase "Modify view template" as UC227
Manager --> UC227
usecase "urban: Add CODT_Inquiry" as UC228
Editor --> UC228
Contributor --> UC228
Manager --> UC228
usecase "Delete objects" as UC229
Editor --> UC229
Contributor --> UC229
Manager --> UC229
usecase "Add portal content" as UC230
Editor --> UC230
Contributor --> UC230
Manager --> UC230
usecase "Manage properties" as UC231
Contributor --> UC231
Editor --> UC231
Manager --> UC231
usecase "Access contents information" as UC232
Reader --> UC232
Editor --> UC232
Contributor --> UC232
Manager --> UC232
usecase "View" as UC233
Reader --> UC233
Editor --> UC233
Contributor --> UC233
Manager --> UC233
usecase "Review portal content" as UC234
Reviewer --> UC234
Manager --> UC234
usecase "Modify portal content" as UC235
Editor --> UC235
Contributor --> UC235
Manager --> UC235
usecase "Acces contents information" as UC236
Reader --> UC236
Editor --> UC236
Contributor --> UC236
Manager --> UC236
usecase "Modify view template" as UC237
Manager --> UC237
usecase "urban: Add CODT_Inquiry" as UC238
Editor --> UC238
Contributor --> UC238
Manager --> UC238
usecase "Delete objects" as UC239
Editor --> UC239
Contributor --> UC239
Manager --> UC239
usecase "Add portal content" as UC240
Editor --> UC240
Contributor --> UC240
Manager --> UC240
usecase "Manage properties" as UC241
Contributor --> UC241
Editor --> UC241
Manager --> UC241
usecase "Access contents information" as UC242
Reader --> UC242
Editor --> UC242
Contributor --> UC242
Manager --> UC242
usecase "View" as UC243
Reader --> UC243
Editor --> UC243
Contributor --> UC243
Manager --> UC243
usecase "Review portal content" as UC244
Reviewer --> UC244
Contributor --> UC244
Manager --> UC244
usecase "Modify portal content" as UC245
Editor --> UC245
Contributor --> UC245
Manager --> UC245
usecase "Acces contents information" as UC246
Reader --> UC246
Editor --> UC246
Contributor --> UC246
Manager --> UC246
usecase "Modify view template" as UC247
Manager --> UC247
usecase "urban: Add CODT_Inquiry" as UC248
Editor --> UC248
Contributor --> UC248
Manager --> UC248
usecase "Delete objects" as UC249
Editor --> UC249
Contributor --> UC249
Manager --> UC249
usecase "Add portal content" as UC250
Editor --> UC250
Contributor --> UC250
Manager --> UC250
usecase "Manage properties" as UC251
Contributor --> UC251
Editor --> UC251
Manager --> UC251
usecase "Access contents information" as UC252
Reader --> UC252
Editor --> UC252
Contributor --> UC252
Manager --> UC252
usecase "View" as UC253
Reader --> UC253
Editor --> UC253
Contributor --> UC253
Manager --> UC253
usecase "Review portal content" as UC254
Reviewer --> UC254
Manager --> UC254
usecase "Modify portal content" as UC255
Editor --> UC255
Contributor --> UC255
Manager --> UC255
usecase "Acces contents information" as UC256
Reader --> UC256
Editor --> UC256
Contributor --> UC256
Manager --> UC256
usecase "Modify view template" as UC257
Manager --> UC257
usecase "urban: Add CODT_Inquiry" as UC258
Editor --> UC258
Contributor --> UC258
Manager --> UC258
usecase "Delete objects" as UC259
Editor --> UC259
Contributor --> UC259
Manager --> UC259
usecase "Add portal content" as UC260
Editor --> UC260
Contributor --> UC260
Manager --> UC260
usecase "Manage properties" as UC261
Contributor --> UC261
Editor --> UC261
Manager --> UC261
usecase "Access contents information" as UC262
Reader --> UC262
Editor --> UC262
Contributor --> UC262
Manager --> UC262
usecase "View" as UC263
Reader --> UC263
Editor --> UC263
Contributor --> UC263
Manager --> UC263
usecase "Review portal content" as UC264
Reviewer --> UC264
Contributor --> UC264
Manager --> UC264
usecase "Modify portal content" as UC265
Editor --> UC265
Contributor --> UC265
Manager --> UC265
usecase "Acces contents information" as UC266
Reader --> UC266
Editor --> UC266
Contributor --> UC266
Manager --> UC266
usecase "Modify view template" as UC267
Manager --> UC267
usecase "urban: Add CODT_Inquiry" as UC268
Editor --> UC268
Contributor --> UC268
Manager --> UC268
usecase "Delete objects" as UC269
Editor --> UC269
Contributor --> UC269
Manager --> UC269
usecase "Add portal content" as UC270
Editor --> UC270
Contributor --> UC270
Manager --> UC270
usecase "Manage properties" as UC271
Contributor --> UC271
Editor --> UC271
Manager --> UC271
usecase "Access contents information" as UC272
Reader --> UC272
Editor --> UC272
Contributor --> UC272
Manager --> UC272
usecase "View" as UC273
Reader --> UC273
Editor --> UC273
Contributor --> UC273
Manager --> UC273
usecase "urban: Add UrbanEvent" as UC274
Contributor --> UC274
Editor --> UC274
Manager --> UC274
usecase "ATContentTypes: Add File" as UC275
Contributor --> UC275
Editor --> UC275
Manager --> UC275
usecase "List folder contents" as UC276
Contributor --> UC276
Editor --> UC276
Manager --> UC276
Reader --> UC276
RoadEditor --> UC276
RoadReader --> UC276
usecase "urban: Add Applicant" as UC277
Contributor --> UC277
Editor --> UC277
Manager --> UC277
usecase "urban: Add Couple" as UC278
Contributor --> UC278
Editor --> UC278
Manager --> UC278
usecase "Modify portal content" as UC279
Contributor --> UC279
Editor --> UC279
Manager --> UC279
RoadEditor --> UC279
AddressEditor --> UC279
usecase "urban: Add Contact" as UC280
Contributor --> UC280
Editor --> UC280
Manager --> UC280
usecase "urban: Add CODT_Inquiry" as UC281
Contributor --> UC281
Editor --> UC281
Manager --> UC281
usecase "Delete objects" as UC282
Contributor --> UC282
Editor --> UC282
Manager --> UC282
usecase "Add portal content" as UC283
Contributor --> UC283
Editor --> UC283
Manager --> UC283
Reader --> UC283
usecase "ATContentTypes: Add Image" as UC284
Contributor --> UC284
Editor --> UC284
Manager --> UC284
usecase "View" as UC285
Contributor --> UC285
Editor --> UC285
ExternalReader --> UC285
InternalReader --> UC285
Manager --> UC285
Reader --> UC285
RoadEditor --> UC285
RoadReader --> UC285
usecase "urban: Add Corporation" as UC286
Contributor --> UC286
Editor --> UC286
Manager --> UC286
usecase "Access contents information" as UC287
Contributor --> UC287
Editor --> UC287
ExternalReader --> UC287
InternalReader --> UC287
Manager --> UC287
Reader --> UC287
RoadEditor --> UC287
RoadReader --> UC287
usecase "urban: Add PortionOut" as UC288
AddressEditor --> UC288
Manager --> UC288
usecase "urban: Add UrbanEventOpinionRequest" as UC289
Contributor --> UC289
Editor --> UC289
Manager --> UC289
usecase "Review portal content" as UC290
Reviewer --> UC290
Manager --> UC290
usecase "Modify portal content" as UC291
Editor --> UC291
Contributor --> UC291
Manager --> UC291
usecase "Acces contents information" as UC292
Reader --> UC292
Editor --> UC292
Contributor --> UC292
Manager --> UC292
usecase "Modify view template" as UC293
Manager --> UC293
usecase "urban: Add CODT_Inquiry" as UC294
Editor --> UC294
Contributor --> UC294
Manager --> UC294
usecase "Delete objects" as UC295
Editor --> UC295
Contributor --> UC295
Manager --> UC295
usecase "Add portal content" as UC296
Editor --> UC296
Contributor --> UC296
Manager --> UC296
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC297
Editor --> UC297
Contributor --> UC297
Manager --> UC297
usecase "View" as UC298
Reader --> UC298
Editor --> UC298
Contributor --> UC298
Manager --> UC298
usecase "Access contents information" as UC299
Reader --> UC299
Editor --> UC299
Contributor --> UC299
Manager --> UC299
usecase "Manage properties" as UC300
Contributor --> UC300
Editor --> UC300
Manager --> UC300
usecase "Review portal content" as UC301
Reviewer --> UC301
Manager --> UC301
usecase "Modify portal content" as UC302
Editor --> UC302
Contributor --> UC302
Manager --> UC302
usecase "Acces contents information" as UC303
Reader --> UC303
Editor --> UC303
Contributor --> UC303
Manager --> UC303
usecase "Modify view template" as UC304
Manager --> UC304
usecase "urban: Add CODT_Inquiry" as UC305
Editor --> UC305
Contributor --> UC305
Manager --> UC305
usecase "Delete objects" as UC306
Editor --> UC306
Contributor --> UC306
Manager --> UC306
usecase "Add portal content" as UC307
Editor --> UC307
Contributor --> UC307
Manager --> UC307
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC308
Editor --> UC308
Contributor --> UC308
Manager --> UC308
usecase "View" as UC309
Reader --> UC309
Editor --> UC309
Contributor --> UC309
Manager --> UC309
usecase "Access contents information" as UC310
Reader --> UC310
Editor --> UC310
Contributor --> UC310
Manager --> UC310
usecase "Manage properties" as UC311
Contributor --> UC311
Editor --> UC311
Manager --> UC311
usecase "Review portal content" as UC312
Reviewer --> UC312
Manager --> UC312
usecase "Modify portal content" as UC313
Editor --> UC313
Contributor --> UC313
Manager --> UC313
usecase "Acces contents information" as UC314
Reader --> UC314
Editor --> UC314
Contributor --> UC314
Manager --> UC314
usecase "Modify view template" as UC315
Manager --> UC315
usecase "urban: Add CODT_Inquiry" as UC316
Editor --> UC316
Contributor --> UC316
Manager --> UC316
usecase "Delete objects" as UC317
Editor --> UC317
Contributor --> UC317
Manager --> UC317
usecase "Add portal content" as UC318
Editor --> UC318
Contributor --> UC318
Manager --> UC318
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC319
Editor --> UC319
Contributor --> UC319
Manager --> UC319
usecase "View" as UC320
Reader --> UC320
Editor --> UC320
Contributor --> UC320
Manager --> UC320
usecase "Access contents information" as UC321
Reader --> UC321
Editor --> UC321
Contributor --> UC321
Manager --> UC321
usecase "Manage properties" as UC322
Contributor --> UC322
Editor --> UC322
Manager --> UC322
usecase "List folder contents" as UC323
Contributor --> UC323
Editor --> UC323
ExternalReader --> UC323
InternalReader --> UC323
Manager --> UC323
Reader --> UC323
RoadEditor --> UC323
RoadReader --> UC323
usecase "liege.urban: Internal Editor" as UC324
Contributor --> UC324
Editor --> UC324
Manager --> UC324
usecase "liege.urban: External Reader" as UC325
Contributor --> UC325
Editor --> UC325
ExternalReader --> UC325
InternalReader --> UC325
Manager --> UC325
Reader --> UC325
RoadReader --> UC325
usecase "Delete objects" as UC326
Contributor --> UC326
Editor --> UC326
Manager --> UC326
usecase "ATContentTypes: Add File" as UC327
Contributor --> UC327
Editor --> UC327
Manager --> UC327
usecase "urban: Add Contact" as UC328
Contributor --> UC328
Editor --> UC328
Manager --> UC328
usecase "liege.urban: Internal Reader" as UC329
Contributor --> UC329
Editor --> UC329
Manager --> UC329
InternalReader --> UC329
usecase "liege.urban: Description Editor" as UC330
Contributor --> UC330
Editor --> UC330
Manager --> UC330
AddressEditor --> UC330
usecase "View" as UC331
Contributor --> UC331
Editor --> UC331
ExternalReader --> UC331
InternalReader --> UC331
Manager --> UC331
Reader --> UC331
RoadReader --> UC331
usecase "ATContentTypes: Add Image" as UC332
Contributor --> UC332
Editor --> UC332
Manager --> UC332
usecase "urban: Add UrbanEvent" as UC333
Contributor --> UC333
Editor --> UC333
Manager --> UC333
usecase "liege.urban: Validate" as UC334
Contributor --> UC334
Manager --> UC334
usecase "liege.urban: Habitation Editor" as UC335
Manager --> UC335
AddressEditor --> UC335
usecase "urban: Add Applicant" as UC336
Contributor --> UC336
Editor --> UC336
Manager --> UC336
usecase "urban: Add CODT_Inquiry" as UC337
Contributor --> UC337
Editor --> UC337
Manager --> UC337
usecase "liege.urban: Road Reader" as UC338
Contributor --> UC338
Editor --> UC338
Manager --> UC338
Reader --> UC338
RoadEditor --> UC338
RoadReader --> UC338
usecase "liege.urban: Road Editor" as UC339
Contributor --> UC339
Editor --> UC339
Manager --> UC339
RoadEditor --> UC339
usecase "urban: Add Corporation" as UC340
usecase "Modify portal content" as UC341
Contributor --> UC341
Editor --> UC341
Manager --> UC341
AddressEditor --> UC341
usecase "urban: Add Couple" as UC342
Contributor --> UC342
Editor --> UC342
Manager --> UC342
usecase "urban: Add PortionOut" as UC343
AddressEditor --> UC343
Manager --> UC343
usecase "Add portal content" as UC344
Contributor --> UC344
Editor --> UC344
Manager --> UC344
Reader --> UC344
usecase "Access contents information" as UC345
Contributor --> UC345
Editor --> UC345
ExternalReader --> UC345
InternalReader --> UC345
Manager --> UC345
Reader --> UC345
RoadEditor --> UC345
RoadReader --> UC345
usecase "urban: Add UrbanEventOpinionRequest" as UC346
Contributor --> UC346
Editor --> UC346
Manager --> UC346
usecase "Review portal content" as UC347
Reviewer --> UC347
Contributor --> UC347
Manager --> UC347
usecase "Modify portal content" as UC348
Editor --> UC348
Contributor --> UC348
Manager --> UC348
usecase "Acces contents information" as UC349
Reader --> UC349
Editor --> UC349
Contributor --> UC349
Manager --> UC349
usecase "Modify view template" as UC350
Manager --> UC350
usecase "urban: Add CODT_Inquiry" as UC351
Editor --> UC351
Contributor --> UC351
Manager --> UC351
usecase "Delete objects" as UC352
Editor --> UC352
Contributor --> UC352
Manager --> UC352
usecase "Add portal content" as UC353
Editor --> UC353
Contributor --> UC353
Manager --> UC353
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC354
Editor --> UC354
Contributor --> UC354
Manager --> UC354
usecase "View" as UC355
Reader --> UC355
Editor --> UC355
Contributor --> UC355
Manager --> UC355
usecase "Access contents information" as UC356
Reader --> UC356
Editor --> UC356
Contributor --> UC356
Manager --> UC356
usecase "Manage properties" as UC357
Contributor --> UC357
Editor --> UC357
Manager --> UC357
usecase "Review portal content" as UC358
Reviewer --> UC358
Contributor --> UC358
Manager --> UC358
usecase "Modify portal content" as UC359
Editor --> UC359
Contributor --> UC359
Manager --> UC359
usecase "Acces contents information" as UC360
Reader --> UC360
Editor --> UC360
Contributor --> UC360
Manager --> UC360
usecase "Modify view template" as UC361
Manager --> UC361
usecase "urban: Add CODT_Inquiry" as UC362
Editor --> UC362
Contributor --> UC362
Manager --> UC362
usecase "Delete objects" as UC363
Editor --> UC363
Contributor --> UC363
Manager --> UC363
usecase "Add portal content" as UC364
Editor --> UC364
Contributor --> UC364
Manager --> UC364
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC365
Editor --> UC365
Contributor --> UC365
Manager --> UC365
usecase "View" as UC366
Reader --> UC366
Editor --> UC366
Contributor --> UC366
Manager --> UC366
usecase "Access contents information" as UC367
Reader --> UC367
Editor --> UC367
Contributor --> UC367
Manager --> UC367
usecase "Manage properties" as UC368
Contributor --> UC368
Editor --> UC368
Manager --> UC368
usecase "urban: Add UrbanEvent" as UC369
Contributor --> UC369
Editor --> UC369
Manager --> UC369
usecase "ATContentTypes: Add File" as UC370
Contributor --> UC370
Editor --> UC370
Manager --> UC370
usecase "List folder contents" as UC371
Contributor --> UC371
Editor --> UC371
Manager --> UC371
Reader --> UC371
RoadEditor --> UC371
RoadReader --> UC371
usecase "urban: Add Applicant" as UC372
Contributor --> UC372
Editor --> UC372
Manager --> UC372
usecase "urban: Add Couple" as UC373
Contributor --> UC373
Editor --> UC373
Manager --> UC373
usecase "Modify portal content" as UC374
Contributor --> UC374
Editor --> UC374
Manager --> UC374
RoadEditor --> UC374
AddressEditor --> UC374
usecase "urban: Add Contact" as UC375
Contributor --> UC375
Editor --> UC375
Manager --> UC375
usecase "urban: Add CODT_Inquiry" as UC376
Contributor --> UC376
Editor --> UC376
Manager --> UC376
usecase "Delete objects" as UC377
Contributor --> UC377
Editor --> UC377
Manager --> UC377
usecase "Add portal content" as UC378
Contributor --> UC378
Editor --> UC378
Manager --> UC378
Reader --> UC378
usecase "ATContentTypes: Add Image" as UC379
Contributor --> UC379
Editor --> UC379
Manager --> UC379
usecase "View" as UC380
Contributor --> UC380
Editor --> UC380
ExternalReader --> UC380
InternalReader --> UC380
Manager --> UC380
Reader --> UC380
RoadEditor --> UC380
RoadReader --> UC380
usecase "urban: Add Corporation" as UC381
Contributor --> UC381
Editor --> UC381
Manager --> UC381
usecase "Access contents information" as UC382
Contributor --> UC382
Editor --> UC382
ExternalReader --> UC382
InternalReader --> UC382
Manager --> UC382
Reader --> UC382
RoadEditor --> UC382
RoadReader --> UC382
usecase "urban: Add PortionOut" as UC383
AddressEditor --> UC383
Manager --> UC383
usecase "urban: Add UrbanEventOpinionRequest" as UC384
Contributor --> UC384
Editor --> UC384
Manager --> UC384
usecase "Review portal content" as UC385
Reviewer --> UC385
Manager --> UC385
usecase "Modify portal content" as UC386
Editor --> UC386
Contributor --> UC386
Manager --> UC386
usecase "Acces contents information" as UC387
Reader --> UC387
Editor --> UC387
Contributor --> UC387
Manager --> UC387
usecase "Modify view template" as UC388
Manager --> UC388
usecase "urban: Add CODT_Inquiry" as UC389
Editor --> UC389
Contributor --> UC389
Manager --> UC389
usecase "Delete objects" as UC390
Editor --> UC390
Contributor --> UC390
Manager --> UC390
usecase "Add portal content" as UC391
Editor --> UC391
Contributor --> UC391
Manager --> UC391
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC392
Editor --> UC392
Contributor --> UC392
Manager --> UC392
usecase "View" as UC393
Reader --> UC393
Editor --> UC393
Contributor --> UC393
Manager --> UC393
usecase "Access contents information" as UC394
Reader --> UC394
Editor --> UC394
Contributor --> UC394
Manager --> UC394
usecase "Manage properties" as UC395
Contributor --> UC395
Editor --> UC395
Manager --> UC395
usecase "Review portal content" as UC396
Reviewer --> UC396
Manager --> UC396
usecase "Modify portal content" as UC397
Editor --> UC397
Contributor --> UC397
Manager --> UC397
usecase "Acces contents information" as UC398
Reader --> UC398
Editor --> UC398
Contributor --> UC398
Manager --> UC398
usecase "Modify view template" as UC399
Manager --> UC399
usecase "urban: Add CODT_Inquiry" as UC400
Editor --> UC400
Contributor --> UC400
Manager --> UC400
usecase "Delete objects" as UC401
Editor --> UC401
Contributor --> UC401
Manager --> UC401
usecase "Add portal content" as UC402
Editor --> UC402
Contributor --> UC402
Manager --> UC402
usecase "urban: Add CODT_UniqueLicenceInquiry" as UC403
Editor --> UC403
Contributor --> UC403
Manager --> UC403
usecase "View" as UC404
Reader --> UC404
Editor --> UC404
Contributor --> UC404
Manager --> UC404
usecase "Access contents information" as UC405
Reader --> UC405
Editor --> UC405
Contributor --> UC405
Manager --> UC405
usecase "Manage properties" as UC406
Contributor --> UC406
Editor --> UC406
Manager --> UC406
usecase "WebDAV Lock items" as UC407
Editor --> UC407
Contributor --> UC407
Manager --> UC407
usecase "ATContentTypes: Add File" as UC408
Editor --> UC408
Contributor --> UC408
Manager --> UC408
Owner --> UC408
usecase "Modify portal content" as UC409
Editor --> UC409
Contributor --> UC409
Manager --> UC409
Owner --> UC409
usecase "WebDAV Unlock items" as UC410
Editor --> UC410
Contributor --> UC410
Manager --> UC410
usecase "Delete objects" as UC411
Editor --> UC411
Contributor --> UC411
Manager --> UC411
Owner --> UC411
usecase "Add portal content" as UC412
Editor --> UC412
Contributor --> UC412
Manager --> UC412
Owner --> UC412
usecase "Access contents information" as UC413
Reader --> UC413
Editor --> UC413
Contributor --> UC413
Manager --> UC413
Owner --> UC413
usecase "ATContentTypes: Add Image" as UC414
Editor --> UC414
Contributor --> UC414
Manager --> UC414
Owner --> UC414
usecase "View" as UC415
Reader --> UC415
Editor --> UC415
Contributor --> UC415
Manager --> UC415
Owner --> UC415
usecase "WebDAV Lock items" as UC416
Editor --> UC416
Contributor --> UC416
Manager --> UC416
usecase "ATContentTypes: Add File" as UC417
Manager --> UC417
usecase "Modify portal content" as UC418
Editor --> UC418
Contributor --> UC418
Manager --> UC418
usecase "WebDAV Unlock items" as UC419
Editor --> UC419
Contributor --> UC419
Manager --> UC419
usecase "Delete objects" as UC420
Editor --> UC420
Contributor --> UC420
Manager --> UC420
usecase "Add portal content" as UC421
Editor --> UC421
Contributor --> UC421
Manager --> UC421
usecase "Access contents information" as UC422
Reader --> UC422
Editor --> UC422
Contributor --> UC422
Manager --> UC422
usecase "ATContentTypes: Add Image" as UC423
Manager --> UC423
usecase "View" as UC424
Reader --> UC424
Editor --> UC424
Contributor --> UC424
Manager --> UC424
usecase "WebDAV Lock items" as UC425
Editor --> UC425
Contributor --> UC425
Manager --> UC425
usecase "ATContentTypes: Add File" as UC426
Editor --> UC426
Contributor --> UC426
Manager --> UC426
usecase "Products.urban: SendToPM" as UC427
Contributor --> UC427
Manager --> UC427
usecase "Modify portal content" as UC428
Editor --> UC428
Contributor --> UC428
Manager --> UC428
usecase "WebDAV Unlock items" as UC429
Editor --> UC429
Contributor --> UC429
Manager --> UC429
usecase "Delete objects" as UC430
Editor --> UC430
Contributor --> UC430
Manager --> UC430
usecase "Add portal content" as UC431
Editor --> UC431
Contributor --> UC431
Manager --> UC431
usecase "Access contents information" as UC432
Reader --> UC432
Editor --> UC432
Contributor --> UC432
Manager --> UC432
usecase "ATContentTypes: Add Image" as UC433
Editor --> UC433
Contributor --> UC433
Manager --> UC433
usecase "View" as UC434
Reader --> UC434
Editor --> UC434
Contributor --> UC434
Manager --> UC434
usecase "Review portal content" as UC435
Editor --> UC435
Contributor --> UC435
Manager --> UC435
Owner --> UC435
usecase "urban: Add UrbanEvent" as UC436
Editor --> UC436
Contributor --> UC436
Manager --> UC436
usecase "Modify portal content" as UC437
Editor --> UC437
Contributor --> UC437
Manager --> UC437
Owner --> UC437
usecase "Acces contents information" as UC438
Reader --> UC438
Contributor --> UC438
Editor --> UC438
Manager --> UC438
Owner --> UC438
usecase "urban: Add Layer" as UC439
Editor --> UC439
Contributor --> UC439
Manager --> UC439
usecase "Delete objects" as UC440
Editor --> UC440
Contributor --> UC440
Manager --> UC440
Owner --> UC440
usecase "Add portal content" as UC441
Editor --> UC441
Contributor --> UC441
Manager --> UC441
usecase "Manage properties" as UC442
Contributor --> UC442
Editor --> UC442
Manager --> UC442
usecase "imio.urban: Add Parcel" as UC443
Editor --> UC443
Contributor --> UC443
Manager --> UC443
usecase "Access contents information" as UC444
Reader --> UC444
Contributor --> UC444
Editor --> UC444
Manager --> UC444
Owner --> UC444
usecase "View" as UC445
Reader --> UC445
Contributor --> UC445
Editor --> UC445
Manager --> UC445
Owner --> UC445
usecase "Review portal content" as UC446
Manager --> UC446
Reviewer --> UC446
usecase "urban: Add UrbanEvent" as UC447
Manager --> UC447
usecase "Modify portal content" as UC448
Manager --> UC448
usecase "Acces contents information" as UC449
Manager --> UC449
Contributor --> UC449
Editor --> UC449
Reader --> UC449
usecase "urban: Add Layer" as UC450
Manager --> UC450
usecase "Modify view template" as UC451
Manager --> UC451
usecase "Delete objects" as UC452
Manager --> UC452
usecase "Add portal content" as UC453
Manager --> UC453
usecase "Manage properties" as UC454
Contributor --> UC454
Editor --> UC454
Manager --> UC454
usecase "imio.urban: Add Parcel" as UC455
Manager --> UC455
usecase "Access contents information" as UC456
Manager --> UC456
Contributor --> UC456
Editor --> UC456
Reader --> UC456
usecase "View" as UC457
Manager --> UC457
Contributor --> UC457
Editor --> UC457
Reader --> UC457
usecase "Review portal content" as UC458
Manager --> UC458
Reviewer --> UC458
usecase "urban: Add UrbanEvent" as UC459
Manager --> UC459
usecase "Modify portal content" as UC460
Manager --> UC460
usecase "Acces contents information" as UC461
Manager --> UC461
Contributor --> UC461
Editor --> UC461
Reader --> UC461
usecase "urban: Add Layer" as UC462
Manager --> UC462
usecase "Modify view template" as UC463
Manager --> UC463
usecase "Delete objects" as UC464
Manager --> UC464
usecase "Add portal content" as UC465
Manager --> UC465
usecase "Manage properties" as UC466
Contributor --> UC466
Editor --> UC466
Manager --> UC466
usecase "imio.urban: Add Parcel" as UC467
Manager --> UC467
usecase "Access contents information" as UC468
Manager --> UC468
Contributor --> UC468
Editor --> UC468
Reader --> UC468
usecase "View" as UC469
Manager --> UC469
Contributor --> UC469
Editor --> UC469
Reader --> UC469
usecase "Review portal content" as UC470
Manager --> UC470
Contributor --> UC470
Editor --> UC470
Owner --> UC470
usecase "ATContentTypes: Add File" as UC471
Manager --> UC471
Contributor --> UC471
Editor --> UC471
Owner --> UC471
usecase "Modify portal content" as UC472
Manager --> UC472
Contributor --> UC472
Editor --> UC472
Owner --> UC472
usecase "Acces contents information" as UC473
Manager --> UC473
Contributor --> UC473
Editor --> UC473
Reader --> UC473
Owner --> UC473
usecase "urban: Add RecipientCadastre" as UC474
Manager --> UC474
Contributor --> UC474
Editor --> UC474
Owner --> UC474
usecase "urban: Add Claimant" as UC475
Manager --> UC475
Contributor --> UC475
Editor --> UC475
Owner --> UC475
usecase "Modify view template" as UC476
Manager --> UC476
usecase "Delete objects" as UC477
Manager --> UC477
Contributor --> UC477
Editor --> UC477
Owner --> UC477
usecase "Add portal content" as UC478
Manager --> UC478
Contributor --> UC478
Editor --> UC478
Owner --> UC478
usecase "ATContentTypes: Add Image" as UC479
Manager --> UC479
Contributor --> UC479
Editor --> UC479
Owner --> UC479
usecase "View" as UC480
Manager --> UC480
Contributor --> UC480
Editor --> UC480
Reader --> UC480
Owner --> UC480
usecase "Review portal content" as UC481
Manager --> UC481
Contributor --> UC481
Editor --> UC481
usecase "ATContentTypes: Add File" as UC482
Manager --> UC482
usecase "Modify portal content" as UC483
Manager --> UC483
usecase "Acces contents information" as UC484
Manager --> UC484
Contributor --> UC484
Editor --> UC484
Reader --> UC484
usecase "urban: Add RecipientCadastre" as UC485
Manager --> UC485
usecase "urban: Add Claimant" as UC486
Manager --> UC486
usecase "Modify view template" as UC487
Manager --> UC487
usecase "Delete objects" as UC488
Manager --> UC488
usecase "Add portal content" as UC489
Manager --> UC489
usecase "Access contents information" as UC490
Manager --> UC490
Contributor --> UC490
Editor --> UC490
Reader --> UC490
usecase "ATContentTypes: Add Image" as UC491
Manager --> UC491
usecase "View" as UC492
Manager --> UC492
Contributor --> UC492
Editor --> UC492
Reader --> UC492
usecase "WebDAV Lock items" as UC493
Editor --> UC493
Contributor --> UC493
Manager --> UC493
usecase "ATContentTypes: Add File" as UC494
Editor --> UC494
Contributor --> UC494
Manager --> UC494
usecase "WebDAV UnLock items" as UC495
Contributor --> UC495
Editor --> UC495
Manager --> UC495
usecase "Modify portal content" as UC496
Editor --> UC496
Contributor --> UC496
Manager --> UC496
usecase "WebDAV Unlock items" as UC497
Editor --> UC497
Contributor --> UC497
Manager --> UC497
usecase "Delete objects" as UC498
Editor --> UC498
Contributor --> UC498
Manager --> UC498
usecase "Add portal content" as UC499
Editor --> UC499
Contributor --> UC499
Manager --> UC499
usecase "Products.urban: Validate" as UC500
Contributor --> UC500
Manager --> UC500
usecase "Access contents information" as UC501
Reader --> UC501
Editor --> UC501
Contributor --> UC501
Manager --> UC501
usecase "ATContentTypes: Add Image" as UC502
Editor --> UC502
Contributor --> UC502
Manager --> UC502
usecase "View" as UC503
Reader --> UC503
Editor --> UC503
Contributor --> UC503
Manager --> UC503
usecase "WebDAV Lock items" as UC504
Editor --> UC504
Contributor --> UC504
Manager --> UC504
usecase "ATContentTypes: Add File" as UC505
Editor --> UC505
Contributor --> UC505
Manager --> UC505
usecase "WebDAV UnLock items" as UC506
Contributor --> UC506
Editor --> UC506
Manager --> UC506
usecase "Modify portal content" as UC507
Editor --> UC507
Contributor --> UC507
Manager --> UC507
usecase "WebDAV Unlock items" as UC508
Editor --> UC508
Contributor --> UC508
Manager --> UC508
usecase "Delete objects" as UC509
Editor --> UC509
Contributor --> UC509
Manager --> UC509
usecase "Add portal content" as UC510
Editor --> UC510
Contributor --> UC510
Manager --> UC510
usecase "Products.urban: Validate" as UC511
Contributor --> UC511
Manager --> UC511
usecase "Access contents information" as UC512
Reader --> UC512
Editor --> UC512
Contributor --> UC512
Manager --> UC512
usecase "ATContentTypes: Add Image" as UC513
Editor --> UC513
Contributor --> UC513
Manager --> UC513
usecase "View" as UC514
Reader --> UC514
Editor --> UC514
Contributor --> UC514
Manager --> UC514
usecase "WebDAV Lock items" as UC515
Editor --> UC515
Contributor --> UC515
Manager --> UC515
usecase "ATContentTypes: Add File" as UC516
Editor --> UC516
Contributor --> UC516
Manager --> UC516
Owner --> UC516
usecase "Modify portal content" as UC517
Editor --> UC517
Contributor --> UC517
Manager --> UC517
Owner --> UC517
usecase "WebDAV UnLock items" as UC518
Contributor --> UC518
Editor --> UC518
Manager --> UC518
usecase "Delete objects" as UC519
Editor --> UC519
Contributor --> UC519
Manager --> UC519
Owner --> UC519
usecase "Add portal content" as UC520
Editor --> UC520
Contributor --> UC520
Manager --> UC520
Owner --> UC520
usecase "Products.urban: Validate" as UC521
Contributor --> UC521
Manager --> UC521
usecase "Access contents information" as UC522
Reader --> UC522
Editor --> UC522
Contributor --> UC522
Manager --> UC522
Owner --> UC522
usecase "ATContentTypes: Add Image" as UC523
Editor --> UC523
Contributor --> UC523
Manager --> UC523
Owner --> UC523
usecase "View" as UC524
Reader --> UC524
Editor --> UC524
Contributor --> UC524
Manager --> UC524
Owner --> UC524
usecase "WebDAV Lock items" as UC525
Editor --> UC525
Contributor --> UC525
Manager --> UC525
usecase "ATContentTypes: Add File" as UC526
Manager --> UC526
usecase "WebDAV UnLock items" as UC527
Contributor --> UC527
Editor --> UC527
Manager --> UC527
usecase "Modify portal content" as UC528
Manager --> UC528
usecase "WebDAV Unlock items" as UC529
Editor --> UC529
Contributor --> UC529
Manager --> UC529
usecase "Delete objects" as UC530
Manager --> UC530
usecase "Add portal content" as UC531
Manager --> UC531
usecase "Products.urban: Validate" as UC532
Editor --> UC532
Contributor --> UC532
Manager --> UC532
usecase "Access contents information" as UC533
Reader --> UC533
Editor --> UC533
Contributor --> UC533
Manager --> UC533
usecase "ATContentTypes: Add Image" as UC534
Manager --> UC534
usecase "View" as UC535
Reader --> UC535
Editor --> UC535
Contributor --> UC535
Manager --> UC535
usecase "Review portal content" as UC536
Reviewer --> UC536
Manager --> UC536
usecase "Modify portal content" as UC537
Editor --> UC537
Contributor --> UC537
Manager --> UC537
usecase "Acces contents information" as UC538
Reader --> UC538
Editor --> UC538
Contributor --> UC538
Manager --> UC538
usecase "Modify view template" as UC539
Manager --> UC539
usecase "Delete objects" as UC540
Editor --> UC540
Contributor --> UC540
Manager --> UC540
usecase "Add portal content" as UC541
Editor --> UC541
Contributor --> UC541
Manager --> UC541
usecase "Manage properties" as UC542
Contributor --> UC542
Editor --> UC542
Manager --> UC542
usecase "Access contents information" as UC543
Reader --> UC543
Editor --> UC543
Contributor --> UC543
Manager --> UC543
usecase "View" as UC544
Reader --> UC544
Editor --> UC544
Contributor --> UC544
Manager --> UC544
usecase "Review portal content" as UC545
Reviewer --> UC545
Contributor --> UC545
Manager --> UC545
usecase "Modify portal content" as UC546
Editor --> UC546
Contributor --> UC546
Manager --> UC546
usecase "Acces contents information" as UC547
Reader --> UC547
Editor --> UC547
Contributor --> UC547
Manager --> UC547
usecase "Modify view template" as UC548
Manager --> UC548
usecase "Delete objects" as UC549
Editor --> UC549
Contributor --> UC549
Manager --> UC549
usecase "Add portal content" as UC550
Editor --> UC550
Contributor --> UC550
Manager --> UC550
usecase "Manage properties" as UC551
Contributor --> UC551
Editor --> UC551
Manager --> UC551
usecase "Access contents information" as UC552
Reader --> UC552
Editor --> UC552
Contributor --> UC552
Manager --> UC552
usecase "View" as UC553
Reader --> UC553
Editor --> UC553
Contributor --> UC553
Manager --> UC553
usecase "Review portal content" as UC554
Reviewer --> UC554
Contributor --> UC554
Manager --> UC554
usecase "Modify portal content" as UC555
Editor --> UC555
Contributor --> UC555
Manager --> UC555
usecase "Acces contents information" as UC556
Reader --> UC556
Editor --> UC556
Contributor --> UC556
Manager --> UC556
usecase "Modify view template" as UC557
Manager --> UC557
usecase "Delete objects" as UC558
Editor --> UC558
Contributor --> UC558
Manager --> UC558
usecase "Add portal content" as UC559
Editor --> UC559
Contributor --> UC559
Manager --> UC559
usecase "Access contents information" as UC560
Reader --> UC560
Editor --> UC560
Contributor --> UC560
Manager --> UC560
usecase "View" as UC561
Reader --> UC561
Editor --> UC561
Contributor --> UC561
Manager --> UC561
usecase "Review portal content" as UC562
Reviewer --> UC562
Contributor --> UC562
Manager --> UC562
usecase "Modify portal content" as UC563
Editor --> UC563
Contributor --> UC563
Manager --> UC563
usecase "Acces contents information" as UC564
Reader --> UC564
Editor --> UC564
Contributor --> UC564
Manager --> UC564
usecase "Modify view template" as UC565
Manager --> UC565
usecase "Delete objects" as UC566
Editor --> UC566
Contributor --> UC566
Manager --> UC566
usecase "Add portal content" as UC567
Editor --> UC567
Contributor --> UC567
Manager --> UC567
usecase "Manage properties" as UC568
Contributor --> UC568
Editor --> UC568
Manager --> UC568
usecase "Access contents information" as UC569
Reader --> UC569
Editor --> UC569
Contributor --> UC569
Manager --> UC569
usecase "View" as UC570
Reader --> UC570
Editor --> UC570
Contributor --> UC570
Manager --> UC570
usecase "urban: Add UrbanEvent" as UC571
Contributor --> UC571
Editor --> UC571
Manager --> UC571
usecase "liege.urban: Validate" as UC572
Contributor --> UC572
Manager --> UC572
usecase "ATContentTypes: Add File" as UC573
Contributor --> UC573
Editor --> UC573
Manager --> UC573
usecase "List folder contents" as UC574
Contributor --> UC574
Editor --> UC574
ExternalReader --> UC574
Manager --> UC574
Reader --> UC574
usecase "urban: Add Applicant" as UC575
Contributor --> UC575
Editor --> UC575
Manager --> UC575
usecase "liege.urban: Internal Editor" as UC576
Contributor --> UC576
Editor --> UC576
Manager --> UC576
usecase "Modify portal content" as UC577
Contributor --> UC577
Editor --> UC577
Manager --> UC577
usecase "liege.urban: External Reader" as UC578
Contributor --> UC578
Editor --> UC578
Manager --> UC578
Reader --> UC578
usecase "urban: Add Contact" as UC579
Contributor --> UC579
Editor --> UC579
Manager --> UC579
usecase "urban: Add CODT_Inquiry" as UC580
Contributor --> UC580
Editor --> UC580
Manager --> UC580
usecase "Delete objects" as UC581
Contributor --> UC581
Editor --> UC581
Manager --> UC581
usecase "Add portal content" as UC582
Contributor --> UC582
Editor --> UC582
Manager --> UC582
Reader --> UC582
usecase "Manage properties" as UC583
Contributor --> UC583
Editor --> UC583
Manager --> UC583
usecase "liege.urban: Internal Reader" as UC584
Contributor --> UC584
Editor --> UC584
Manager --> UC584
Reader --> UC584
usecase "urban: Add UrbanEventInspectionReport" as UC585
Contributor --> UC585
Editor --> UC585
Manager --> UC585
usecase "View" as UC586
Contributor --> UC586
Editor --> UC586
ExternalReader --> UC586
Manager --> UC586
Reader --> UC586
usecase "urban: Add Corporation" as UC587
Contributor --> UC587
Editor --> UC587
Manager --> UC587
usecase "Access contents information" as UC588
Contributor --> UC588
Editor --> UC588
ExternalReader --> UC588
Manager --> UC588
Reader --> UC588
usecase "ATContentTypes: Add Image" as UC589
Contributor --> UC589
Editor --> UC589
Manager --> UC589
usecase "urban: Add UrbanEventOpinionRequest" as UC590
Contributor --> UC590
Editor --> UC590
Manager --> UC590
usecase "urban: Add UrbanEvent" as UC591
Contributor --> UC591
Editor --> UC591
Manager --> UC591
usecase "liege.urban: Validate" as UC592
Contributor --> UC592
Manager --> UC592
usecase "ATContentTypes: Add File" as UC593
Contributor --> UC593
Editor --> UC593
Manager --> UC593
usecase "List folder contents" as UC594
Contributor --> UC594
Editor --> UC594
ExternalReader --> UC594
Manager --> UC594
Reader --> UC594
usecase "urban: Add Applicant" as UC595
Contributor --> UC595
Editor --> UC595
Manager --> UC595
usecase "liege.urban: Internal Editor" as UC596
Contributor --> UC596
Editor --> UC596
Manager --> UC596
usecase "Modify portal content" as UC597
Contributor --> UC597
Editor --> UC597
Manager --> UC597
usecase "liege.urban: External Reader" as UC598
Contributor --> UC598
Editor --> UC598
ExternalReader --> UC598
Manager --> UC598
Reader --> UC598
usecase "urban: Add Contact" as UC599
Contributor --> UC599
Editor --> UC599
Manager --> UC599
usecase "urban: Add CODT_Inquiry" as UC600
Contributor --> UC600
Editor --> UC600
Manager --> UC600
usecase "Delete objects" as UC601
Contributor --> UC601
Editor --> UC601
Manager --> UC601
usecase "Add portal content" as UC602
Contributor --> UC602
Editor --> UC602
Manager --> UC602
Reader --> UC602
usecase "Manage properties" as UC603
Contributor --> UC603
Editor --> UC603
Manager --> UC603
usecase "liege.urban: Internal Reader" as UC604
Contributor --> UC604
Editor --> UC604
Manager --> UC604
Reader --> UC604
usecase "urban: Add UrbanEventInspectionReport" as UC605
Contributor --> UC605
Editor --> UC605
Manager --> UC605
usecase "View" as UC606
Contributor --> UC606
Editor --> UC606
ExternalReader --> UC606
Manager --> UC606
Reader --> UC606
usecase "urban: Add Corporation" as UC607
Contributor --> UC607
Editor --> UC607
Manager --> UC607
usecase "Access contents information" as UC608
Contributor --> UC608
Editor --> UC608
ExternalReader --> UC608
Manager --> UC608
Reader --> UC608
usecase "ATContentTypes: Add Image" as UC609
Contributor --> UC609
Editor --> UC609
Manager --> UC609
usecase "urban: Add UrbanEventOpinionRequest" as UC610
Contributor --> UC610
Editor --> UC610
Manager --> UC610
usecase "urban: Add UrbanEvent" as UC611
Contributor --> UC611
Editor --> UC611
Manager --> UC611
usecase "liege.urban: Validate" as UC612
Contributor --> UC612
Manager --> UC612
usecase "ATContentTypes: Add File" as UC613
Contributor --> UC613
Editor --> UC613
Manager --> UC613
usecase "List folder contents" as UC614
Contributor --> UC614
Editor --> UC614
ExternalReader --> UC614
Manager --> UC614
Reader --> UC614
usecase "urban: Add Applicant" as UC615
Contributor --> UC615
Editor --> UC615
Manager --> UC615
usecase "liege.urban: Internal Editor" as UC616
Contributor --> UC616
Editor --> UC616
Manager --> UC616
usecase "Modify portal content" as UC617
Contributor --> UC617
Editor --> UC617
Manager --> UC617
usecase "liege.urban: External Reader" as UC618
Contributor --> UC618
Editor --> UC618
Manager --> UC618
Reader --> UC618
usecase "urban: Add Contact" as UC619
Contributor --> UC619
Editor --> UC619
Manager --> UC619
usecase "urban: Add CODT_Inquiry" as UC620
Contributor --> UC620
Editor --> UC620
Manager --> UC620
usecase "Delete objects" as UC621
Contributor --> UC621
Editor --> UC621
Manager --> UC621
usecase "Add portal content" as UC622
Contributor --> UC622
Editor --> UC622
Manager --> UC622
Reader --> UC622
usecase "Manage properties" as UC623
Contributor --> UC623
Editor --> UC623
Manager --> UC623
usecase "liege.urban: Internal Reader" as UC624
Contributor --> UC624
Editor --> UC624
Manager --> UC624
Reader --> UC624
usecase "urban: Add UrbanEventInspectionReport" as UC625
Contributor --> UC625
Editor --> UC625
Manager --> UC625
usecase "View" as UC626
Contributor --> UC626
Editor --> UC626
ExternalReader --> UC626
Manager --> UC626
Reader --> UC626
usecase "urban: Add Corporation" as UC627
Contributor --> UC627
Editor --> UC627
Manager --> UC627
usecase "Access contents information" as UC628
Contributor --> UC628
Editor --> UC628
ExternalReader --> UC628
Manager --> UC628
Reader --> UC628
usecase "ATContentTypes: Add Image" as UC629
Contributor --> UC629
Editor --> UC629
Manager --> UC629
usecase "urban: Add UrbanEventOpinionRequest" as UC630
Contributor --> UC630
Editor --> UC630
Manager --> UC630
usecase "urban: Add UrbanEvent" as UC631
Contributor --> UC631
Editor --> UC631
Manager --> UC631
usecase "liege.urban: Validate" as UC632
Contributor --> UC632
Manager --> UC632
usecase "ATContentTypes: Add File" as UC633
Contributor --> UC633
Editor --> UC633
Manager --> UC633
usecase "List folder contents" as UC634
Contributor --> UC634
Editor --> UC634
ExternalReader --> UC634
Manager --> UC634
Reader --> UC634
usecase "urban: Add Applicant" as UC635
Contributor --> UC635
Editor --> UC635
Manager --> UC635
usecase "liege.urban: Internal Editor" as UC636
Contributor --> UC636
Editor --> UC636
Manager --> UC636
usecase "Modify portal content" as UC637
Contributor --> UC637
Editor --> UC637
Manager --> UC637
usecase "liege.urban: External Reader" as UC638
Contributor --> UC638
Editor --> UC638
Manager --> UC638
Reader --> UC638
usecase "urban: Add Contact" as UC639
Contributor --> UC639
Editor --> UC639
Manager --> UC639
usecase "urban: Add CODT_Inquiry" as UC640
Contributor --> UC640
Editor --> UC640
Manager --> UC640
usecase "Delete objects" as UC641
Contributor --> UC641
Editor --> UC641
Manager --> UC641
usecase "Add portal content" as UC642
Contributor --> UC642
Editor --> UC642
Manager --> UC642
Reader --> UC642
usecase "Manage properties" as UC643
Contributor --> UC643
Editor --> UC643
Manager --> UC643
usecase "liege.urban: Internal Reader" as UC644
Contributor --> UC644
Editor --> UC644
Manager --> UC644
Reader --> UC644
usecase "urban: Add UrbanEventInspectionReport" as UC645
Contributor --> UC645
Editor --> UC645
Manager --> UC645
usecase "View" as UC646
Contributor --> UC646
Editor --> UC646
ExternalReader --> UC646
Manager --> UC646
Reader --> UC646
usecase "urban: Add Corporation" as UC647
Contributor --> UC647
Editor --> UC647
Manager --> UC647
usecase "Access contents information" as UC648
Contributor --> UC648
Editor --> UC648
ExternalReader --> UC648
Manager --> UC648
Reader --> UC648
usecase "ATContentTypes: Add Image" as UC649
Contributor --> UC649
Editor --> UC649
Manager --> UC649
usecase "urban: Add UrbanEventOpinionRequest" as UC650
Contributor --> UC650
Editor --> UC650
Manager --> UC650
usecase "urban: Add UrbanEvent" as UC651
Contributor --> UC651
Editor --> UC651
Manager --> UC651
usecase "liege.urban: Validate" as UC652
Contributor --> UC652
Manager --> UC652
usecase "ATContentTypes: Add File" as UC653
Contributor --> UC653
Editor --> UC653
Manager --> UC653
usecase "List folder contents" as UC654
Contributor --> UC654
Editor --> UC654
ExternalReader --> UC654
Manager --> UC654
Reader --> UC654
usecase "urban: Add Applicant" as UC655
Contributor --> UC655
Editor --> UC655
Manager --> UC655
usecase "liege.urban: Internal Editor" as UC656
Contributor --> UC656
Editor --> UC656
Manager --> UC656
usecase "Modify portal content" as UC657
Contributor --> UC657
Editor --> UC657
Manager --> UC657
usecase "liege.urban: External Reader" as UC658
Contributor --> UC658
Editor --> UC658
Manager --> UC658
Reader --> UC658
usecase "urban: Add Contact" as UC659
Contributor --> UC659
Editor --> UC659
Manager --> UC659
usecase "urban: Add CODT_Inquiry" as UC660
Contributor --> UC660
Editor --> UC660
Manager --> UC660
usecase "Delete objects" as UC661
Contributor --> UC661
Editor --> UC661
Manager --> UC661
usecase "Add portal content" as UC662
Contributor --> UC662
Editor --> UC662
Manager --> UC662
Reader --> UC662
usecase "Manage properties" as UC663
Contributor --> UC663
Editor --> UC663
Manager --> UC663
usecase "liege.urban: Internal Reader" as UC664
Contributor --> UC664
Editor --> UC664
Manager --> UC664
Reader --> UC664
usecase "urban: Add UrbanEventInspectionReport" as UC665
Contributor --> UC665
Editor --> UC665
Manager --> UC665
usecase "View" as UC666
Contributor --> UC666
Editor --> UC666
ExternalReader --> UC666
Manager --> UC666
Reader --> UC666
usecase "urban: Add Corporation" as UC667
Contributor --> UC667
Editor --> UC667
Manager --> UC667
usecase "Access contents information" as UC668
Contributor --> UC668
Editor --> UC668
ExternalReader --> UC668
Manager --> UC668
Reader --> UC668
usecase "ATContentTypes: Add Image" as UC669
Contributor --> UC669
Editor --> UC669
Manager --> UC669
usecase "urban: Add UrbanEventOpinionRequest" as UC670
Contributor --> UC670
Editor --> UC670
Manager --> UC670
usecase "Review portal content" as UC671
Reviewer --> UC671
Contributor --> UC671
Manager --> UC671
usecase "Modify portal content" as UC672
Editor --> UC672
Contributor --> UC672
Manager --> UC672
usecase "Acces contents information" as UC673
Reader --> UC673
Editor --> UC673
Contributor --> UC673
Manager --> UC673
usecase "Modify view template" as UC674
Manager --> UC674
usecase "Delete objects" as UC675
Editor --> UC675
Contributor --> UC675
Manager --> UC675
usecase "Add portal content" as UC676
Editor --> UC676
Contributor --> UC676
Manager --> UC676
usecase "Manage properties" as UC677
Contributor --> UC677
Editor --> UC677
Manager --> UC677
usecase "Access contents information" as UC678
Reader --> UC678
Editor --> UC678
Contributor --> UC678
Manager --> UC678
usecase "View" as UC679
Reader --> UC679
Editor --> UC679
Contributor --> UC679
Manager --> UC679
usecase "Review portal content" as UC680
Reviewer --> UC680
Contributor --> UC680
Manager --> UC680
usecase "Modify portal content" as UC681
Editor --> UC681
Contributor --> UC681
Manager --> UC681
usecase "Acces contents information" as UC682
Reader --> UC682
Editor --> UC682
Contributor --> UC682
Manager --> UC682
usecase "Modify view template" as UC683
Manager --> UC683
usecase "Delete objects" as UC684
Editor --> UC684
Contributor --> UC684
Manager --> UC684
usecase "Add portal content" as UC685
Editor --> UC685
Contributor --> UC685
Manager --> UC685
usecase "Access contents information" as UC686
Reader --> UC686
Editor --> UC686
Contributor --> UC686
Manager --> UC686
usecase "View" as UC687
Reader --> UC687
Editor --> UC687
Contributor --> UC687
Manager --> UC687
usecase "Review portal content" as UC688
Reviewer --> UC688
Contributor --> UC688
Manager --> UC688
usecase "Modify portal content" as UC689
Editor --> UC689
Contributor --> UC689
Manager --> UC689
usecase "Acces contents information" as UC690
Reader --> UC690
Editor --> UC690
Contributor --> UC690
Manager --> UC690
usecase "Modify view template" as UC691
Manager --> UC691
usecase "Delete objects" as UC692
Editor --> UC692
Contributor --> UC692
Manager --> UC692
usecase "Add portal content" as UC693
Editor --> UC693
Contributor --> UC693
Manager --> UC693
usecase "Manage properties" as UC694
Contributor --> UC694
Editor --> UC694
Manager --> UC694
usecase "Access contents information" as UC695
Reader --> UC695
Editor --> UC695
Contributor --> UC695
Manager --> UC695
usecase "View" as UC696
Reader --> UC696
Editor --> UC696
Contributor --> UC696
Manager --> UC696
usecase "Review portal content" as UC697
Reviewer --> UC697
Contributor --> UC697
Manager --> UC697
usecase "Modify portal content" as UC698
Editor --> UC698
Contributor --> UC698
Manager --> UC698
usecase "Acces contents information" as UC699
Reader --> UC699
Editor --> UC699
Contributor --> UC699
Manager --> UC699
usecase "Modify view template" as UC700
Manager --> UC700
usecase "Delete objects" as UC701
Editor --> UC701
Contributor --> UC701
Manager --> UC701
usecase "Add portal content" as UC702
Editor --> UC702
Contributor --> UC702
Manager --> UC702
usecase "Manage properties" as UC703
Contributor --> UC703
Editor --> UC703
Manager --> UC703
usecase "Access contents information" as UC704
Reader --> UC704
Editor --> UC704
Contributor --> UC704
Manager --> UC704
usecase "View" as UC705
Reader --> UC705
Editor --> UC705
Contributor --> UC705
Manager --> UC705
usecase "Review portal content" as UC706
Reviewer --> UC706
Manager --> UC706
usecase "Modify portal content" as UC707
Editor --> UC707
Contributor --> UC707
Manager --> UC707
usecase "Acces contents information" as UC708
Reader --> UC708
Editor --> UC708
Contributor --> UC708
Manager --> UC708
usecase "Modify view template" as UC709
Manager --> UC709
usecase "Delete objects" as UC710
Editor --> UC710
Contributor --> UC710
Manager --> UC710
usecase "Add portal content" as UC711
Editor --> UC711
Contributor --> UC711
Manager --> UC711
usecase "Manage properties" as UC712
Contributor --> UC712
Editor --> UC712
Manager --> UC712
usecase "Access contents information" as UC713
Reader --> UC713
Editor --> UC713
Contributor --> UC713
Manager --> UC713
usecase "View" as UC714
Reader --> UC714
Editor --> UC714
Contributor --> UC714
Manager --> UC714
usecase "Review portal content" as UC715
Reviewer --> UC715
Contributor --> UC715
Manager --> UC715
usecase "Modify portal content" as UC716
Editor --> UC716
Contributor --> UC716
Manager --> UC716
usecase "Acces contents information" as UC717
Reader --> UC717
Editor --> UC717
Contributor --> UC717
Manager --> UC717
usecase "Modify view template" as UC718
Manager --> UC718
usecase "Delete objects" as UC719
Editor --> UC719
Contributor --> UC719
Manager --> UC719
usecase "Add portal content" as UC720
Editor --> UC720
Contributor --> UC720
Manager --> UC720
usecase "Manage properties" as UC721
Contributor --> UC721
Editor --> UC721
Manager --> UC721
usecase "Access contents information" as UC722
Reader --> UC722
Editor --> UC722
Contributor --> UC722
Manager --> UC722
usecase "View" as UC723
Reader --> UC723
Editor --> UC723
Contributor --> UC723
Manager --> UC723
@enduml
